const rkmidi = require("runkit-midi");

const data = 'data:audio/midi;base64,\
TVRoZAAAAAYAAQADAGRNVHJrAAAAGgD/AwtMaXR0bGUgTGFtZQD/UQMKLCsA/y8A\
TVRyawAAAPMA/wMGTHlyaWNzAP8BGEBUTWFyeSBXYXMgQSBMaXR0bGUgTGFtZWT/\
AQNcTWFL/wEDcnkgGf8BBHdhcyAy/wECYSAy/wEDbGl0Mv8BBHRsZSAy/wEFbGFt\
ZSxk/wEEL0xpdDL/AQR0bGUgMv8BBWxhbWUsZP8BBC9MaXQy/wEEdGxlIDL/AQVs\
YW1lLGT/AQMvTWFL/wEDcnkgGf8BBHdhcyAy/wECYSAy/wEDbGl0Mv8BBHRsZSAy\
/wEFbGFtZSwy/wEDL0EgMv8BA2xpdDL/AQR0bGUgMv8BBWxhbWUgMv8BBHdhcyAy\
/wEEc2hlIQD/LwBNVHJrAAAA8gD/AwVNdXNpYwDAC2SQQH9LgEBAAJA+fxmAPkAA\
kDx/MoA8QACQPn8ygD5AAJBAfzKAQEAAkEB/MoBAQACQQH9agEBACpA+fzKAPkAA\
kD5/MoA+QACQPn9agD5ACpBAfzKAQEAAkEN/MoBDQACQQ39agENACpBAf0uAQEAA\
kD5/GYA+QACQPH8ygDxAAJA+fzKAPkAAkEB/MoBAQACQQH8ygEBAAJBAfzKAQEAZ\
kEB/GYBAQACQPn8ygD5AAJA+fzKAPkAAkEB/MoBAQACQPn8ygD5AAJA8f2RAZABD\
ZABIf1qAPEAAQEAAQ0AASEAK/y8A';

rkmidi(data);
// click the [▶run] button... ↓